config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  devise_for :users

  resources :products, only: %i[index show edit new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
  resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index new show create update destroy edit] do
    resources :order_items, only: %i[create destroy]
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :warehouse

  validates :count, presence: true, numericality: { greater_than: 0 }
end

app/controllers/stocks_controller.rb
class StocksController < AdminController
  before_action :set_stock, only: %i[show]
  before_action :set_form_dependencies, only: %i[new edit]
  before_action :set_warehouse
  def index
    @stocks = Stock.all
  end

  def show; end

  def new
    @stock = Stock.new
  end
  #
  # def create
  #   @stock = @warehouse.stocks.build(stock_params)
  #
  #   if @stock.save
  #     redirect_to warehouse_path(@warehouse)
  #   else
  #     render :new
  #   end
  # end

  def create
    @stock = @warehouse.stocks.find_or_initialize_by(product_id: stock_params[:product_id].to_i)
    if @stock.new_record?
      @stock.count = stock_params[:count].to_i
    else
      @stock.count += stock_params[:count].to_i
    end
    if @stock.save
      render json: @stock.as_json(
        only: %i[id count],
        include: {
          product: {
            only: %i[sku name]
          }
        }
      )
    else
      render json: { errors: @stocks.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find(params[:warehouse_id])
  end

  # def set_form_dependencies
  #   @warehouses = Warehouse.all
  #   @products = Product.all
  # end
  #
  # def set_stock
  #   @stock = Stock.find(params[:id])
  # end

  def stock_params
    params.require(:stock).permit(:product_id, :count)
  end
end

app/views/stocks/_form.html.erb
<%= form_with model: stock, local: true, id: "stock-form", url: warehouse_stocks_path(warehouse) do |f| %>
<div class="form-group">
  <%= f.select :product_id, @products.all.map { |p| [p.name, p.id] } %>
</div>
<div class="form-group">
  <%= f.label :count %>
  <%= f.text_field :count, class: "form-control" %>
</div>
<%= f.submit "Save Stock", class: "btn btn-primary", id: "submit-button" %>
<% end %>

<%# study this! %>

app/views/stocks/edit.html.erb
<div class="container">
  <h1>Editing Stocks (ID: <%= @stock.id %>)</h1>

  <%= render 'form', stock: @stock, products: @products, warehouses: @warehouses %>
</div>

app/views/stocks/index.html.erb
<div class="container">
  <h1>Stocks</h1>

  <%= link_to "New Stock", new_stock_path, class: "btn btn-primary" %>
  <table id="stocks-table" class="table">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Stock Count</th>
        <th>Warehouse</th>
      </tr>
    </thead>
    <tbody>
      <% @stocks.each do |stock| %>
        <tr id="stock--<%= stock.id %>">
          <td id="stock--<%= stock.id %>_product">
            <%= stock.product.name %>
          </td>
          <td id="stock--<%= stock.id %>_count">
            <%= stock.count %>
          </td>
          <td id="stock--<%= stock.id %>_warehouse">
            <%= stock.warehouse.street + " " + stock.warehouse.city + " " + stock.warehouse.province %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stocks/new.html.erb
<div class="container">
  <h1>New Stock</h1>

  <%= render 'form', stock: @stock, products: @products, warehouses: @warehouses %>
</div>

app/views/stocks/show.html.erb
<h1>stock</h1>
<!-- <hr /> -->
<table class="table">
  <tbody>
    <tr>
      <td>warehouse</td>
      <td id="stock--<%= @stock.id %>_warehouse">
        <%= @stock.warehouse.full_address %>
      </td>
    </tr>
    <tr>
      <td>Product</td>
      <td id="stock--<%= @stock.id %>_product">
        <%= @stock.product.name %>
      </td>
    </tr>
    <tr>
      <td>Count</td>
      <td id="stock--<%= @stock.id %>_">
        <%= @stock.count %>
      </td>
    </tr>
  </tbody>
</table>