config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  devise_for :users

  resources :products, only: %i[index show edit new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
  resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index new show create update destroy edit] do
    resources :order_items, only: %i[create destroy]
  end
end

app/views/shared/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="alert alert-<%= flash[:notice].present? ? 'success' : 'danger' %>">
    <%= flash[:notice] || flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <%= link_to "Inventory", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-target="#navbar-content">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-space-between" id="navbar-content">
      <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Products", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Warehouse", warehouses_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Orders", orders_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
      <div class="text-white">
        <% if user_signed_in? %>
          Hi, <%= current_user.email %>!
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
        <% else %>
          <%= link_to "Sign In", user_session_path, class: "btn btn-success" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>