config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  devise_for :users

  resources :products, only: %i[index show edit new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
  resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index new show create update destroy edit] do
    resources :order_items, only: %i[create destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :customer_name, presence: true

  before_validation :assign_uuid

  private

  def assign_uuid
    return unless new_record? || uuid.empty?

    generated_uuid = ''
    presence = true
    while presence == true
      generated_uuid = SecureRandom.uuid
      presence = false unless Order.exists?(uuid: generated_uuid)
    end
    self.uuid = generated_uuid
  end
end

app/controllers/orders_controller.rb
class OrdersController < AdminController
  before_action :set_orders, only: %i[show destroy edit update]
  before_action :set_dependencies, only: %i[new edit show update create]
  def index
    @orders = Order.all
  end
  def new
    @order = Order.new
  end

  def show
    @order_item = @order.order_items.new

    respond_to do |format|
      format.json { render json: @order }
      format.html
    end
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash.notice = 'Successfully created an order!'
      redirect_to order_path(@order)
    else
      render :new
    end
  end
  
  def edit; end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order #{@order.id} was successfully deleted." }
    end
  end

  private

  def set_orders
    @order = Order.find(params[:id])
  end
  def set_dependencies
    @warehouses = Warehouse.all
    @products = Product.all
  end
  def order_params
    params.require(:order).permit(:warehouse_id, :customer_name)
  end

app/views/orders/_form.html.erb
<%= form_with model: order, local: true, id: "new_order_form" do |f| %>
  <div class="form-group">
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :warehouse %>
    <%= f.select :warehouse_id,
                 warehouses.map { |warehouse| [warehouse.full_address, warehouse.id] },
                 {},
                 { class: "form-control" } %>
  </div>
  <%= f.submit "Save Order", class: "btn btn-success" %>
<% end %>

app/views/orders/index.html.erb
<div class="container">
  <%= link_to "New Order", new_order_path, class: "btn btn-primary" %>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Customer Name</th>
        <th>Warehouse</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.customer_name %></td>
          <td><%= order.warehouse.full_address %></td>
          <td>
            <%= link_to "Show", order_path(order) %>
            <%= link_to "Edit", edit_order_path(order) %>
            <%= link_to "Delete", order_path(order), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="container">
  <h2>New Order</h2>
  <%= render "form", order: @order, warehouses: @warehouses %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h2>Order (ID: <%= @order.id %>)</h2>
  <small>Customer</small>
  <h4><%= @order.customer_name %></h4>
  <small>Warehouse<small>
  <h4><%= @order.warehouse.full_address %></h4>

  <hr />

  <div class="container">
    <dl class="row">
      <dt class="col-sm-2">Name</dt>
      <dd class="col-sm-10" id=<%= "order--#{@order.id}_customer_name" %> ><%= @order.customer_name %></dd>
      <dt class="col-sm-2">Warehouse</dt>
      <dd class="col-sm-10" id=<%= "order--#{@order.id}_full_address" %> ><%= "#{@order.warehouse.full_address}" %></dd>
    </dl>
  </div>
  <div class="container">
    <%= react_component "Order",
        {
          id: @order.id,
          order_items: @order.order_items.as_json(
            only: %i[id quantity],
            include: {
              product: {
                only: %i[sku name]
              }
            }
          )
        } %>
  </div>
  <div class="container">
    <%= link_to 'Back', orders_path, class: 'btn btn-danger' %>
  </div>


</div>