config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  devise_for :users

  resources :products, only: %i[index show edit new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
  resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index new show create update destroy edit] do
    resources :order_items, only: %i[create destroy]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :stocks
  has_many :warehouses, through: :stocks
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  validates :name, presence: true
  validates :sku, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/products_controller.rb
class ProductsController < AdminController
  before_action :assign_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show; end

  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash.notice = 'Successfully created a product.'

      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      flash.notice = 'Successfully updated product.'

      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy!

    flash.notice = "Successfully deleted product #{@product.id}."
    redirect_to products_path
  end

  private

  def assign_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :sku)
  end
end

app/views/products/_form.html.erb
<%= form_with model: product, local: true, id: "product-form" do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= render_error(product, :name) %>
  </div>
  <div class="form-group">
    <%= f.label :sku %>
    <%= f.text_field :sku, class: "form-control" %>
    <%= render_error(product, :sku) %>
  </div>
  <%= f.submit "Save Product", class: "btn btn-primary", id: "submit-button" %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing Product (ID: <%= @product.id %>)</h1>

  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<div class="container">
  <h1>Products</h1>
  <%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>
  <table id= "products-table" class="table">
    <thead>
      <tr>
        <th>SKU</th>
        <th>Name</th>
        <th>Updated At</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr id = "product--<%= product.id %>">
        <td id = "product--<%= product.id %>_sku">
          <%= product.sku %>
        </td>
        <td id = "product--<%= product.id %>_name">
          <%= product.name %>
        </td>
        <td id = "product--<%= product.id %>_updated_at">
          <%= product.updated_at.strftime('%m-%d-%Y') %>
        </td>
        <td id = "product--<%= product.id %>_actions">
          <%= link_to "Show", product_path(product) %>
          <%= link_to "Edit", edit_product_path(product) %>
          <%= link_to "Delete",
                      product_path(product),
                      class: 'delete',
                      method: :delete,
                      data: {
                        confirm: "Are you sure you want to delete this product?"
                      } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>

  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<h1>Product</h1>
<!-- <hr /> -->
<table class="table">
  <tbody>
    <tr>
      <td>Name</td>
      <td id="product--<%= @product.id %>_name">
        <%= @product.name %>
      </td>
    </tr>
    <tr>
      <td>SKU</td>
      <td id="product--<%= @product.id %>_sku">
        <%= @product.sku %>
      </td>
    </tr>
  </tbody>
</table>

<table class="table">
  <tbody>
    <tr>
      <td>Address</td>
      <td><% @product.warehouses.each do |warehouse| %>
        <td><%= warehouse.full_address%></td>
        <td><%= warehouse.inventory_count(@product)%></td>
        <% end %>
      </td>
        <%= @product.name %>
    </tr>
  </tbody>
</table>